### ISSUE TITLE
Section on bibtex and citing in markdown

### ISSUE THREAD

**Issue by chartgerink** [libscie/rmarkdown-workshop#4]
Still need to add a short description on bibtex and how to cite in rmarkdown.

Maybe also add something about citation styles in Rmarkdown (.csl files), but don't know how that interacts with the papaja stuff #3 (I don't use papaja because I dislike the APA style manuscript straitjacket).

@mcfrank

**Comment by crsh** [comment]
You can specify CSL styles in `papaja` to overwrite the default `apa6` style as in any other R Markdown document.

Maybe it's worth mentioning my [`citr`](github.com/crsh/citr) package here as well?
